const odpisoveskupiny = [
    {
        cislo: 0,
        dobaodpisovania: 2,
        dobaodpisovaniapripona: "roky",
        coodpisujeme: [
            "Elektromobily",
            "Hybridné automobily",
        ],
    },
    {
        cislo: 1,
        dobaodpisovania: 4,
        dobaodpisovaniapripona: "roky",
        coodpisujeme: [
            "Živé dojnice, ostatných hovädzí dobytok a byvoly okrem teliat (živé), ovce a kozy, ošípané, husi (živé)",
            "Nepremokavé plachty, ochranné a tieniace plachty",
            "Ostatné keramické výrobky na technické účely",
            "Počítače a periférne zariadenia",
            "Komunikačné zariadenia",
            "Spotrebná elektronika",
            "Meracie, testovacie a navigačné zariadenia",
            "Kancelárske stroje a zariadenia",
            "Optické a fotografické prístroje a zariadenia",
            "Ručné nástroje",
            "Stroje pre poľnohospodárstvo a lesníctvo",
            "Stroje pre textilný, odevný a kožiarsky, priemysel",
            "Osobné automobily",
            "Motorové vozidlá na prepravu desať a viac osôb (autobusy) okrem trolejbusov a elektrobusov",
            "Motorové vozidlá na prepravu nákladu",
            "Bicykle a vozíky pre invalidov",
            "Hry a hračky okrem \"ostatné hry\"",
            "Výrobky inde nezaradené",
        ],
    },
    {
        cislo: 2,
        dobaodpisovania: 6,
        dobaodpisovaniapripona: "rokov",
        zrychlene: true,
        coodpisujeme: [
            "Živé kone",
            "Montované stavby z dreva – ak nie sú samostatnými stavebnými objektmi",
            "Montované stavby z plastu – ak nie sú samostatnými stavebnými objektmi",
            "Radiátory a kotly ústredného kúrenia",
            "Nožiarske výrobky, nástroje a železiarsky tovar",
            "Ostatné kovové výrobky",
            "Hodiny a hodinky",
            "Prístroje na ožarovanie, elektromedicínske a elektroterapeutické prístroje",
            "Batérie a akumulátory",
            "Elektrické svietidlá",
            "Prístroje pre domácnosť",
            "Ostatné elektrické zariadenia",
            "Zdvíhacie a manipulačné zariadenia",
            "Chladiace zariadenia",
            "Stroje na tvarovanie kovov a obrábanie",
            "Trolejbusy a autobusy",
            "Motocykle a prívesné vozíky",
            "Nábytok",
            "Hudobné nástroje",
            "Športové výrobky",
        ],
    },
    {
        cislo: 3,
        dobaodpisovania: 8,
        dobaodpisovaniapripona: "rokov",
        zrychlene: true,
        coodpisujeme: [
            "Elektrické motory, generátory a transformátory a elektrické rozvodné a ovládacie zariadenia",
            "Zážihové spaľovacie lodné motory, ostatné motory",
            "Ostatné piestové vznetové motory s vnútorným spaľovaním",
            "Turbíny",
            "Pece, horáky a ich časti",
            "Chladiace a vetracie zariadenia okrem zariadení pre domácnosť",
            "Plynové generátory, destilačné a filtračné prístroje",
            "Stroje pre metalurgiu",
        ],
    },
    {
        cislo: 4,
        dobaodpisovania: 12,
        dobaodpisovaniapripona: "rokov",
        coodpisujeme: [
            "Montované budovy z betónu, ak nie sú samostatnými stavebnými objektmi pripojenými na inžinierske siete",
            "Montované budovy z kovov, ak nie sú samostatnými stavebnými objektmi pripojenými na inžinierske siete",
            "Ostatné nádrže, zásobníky a kontajnery z kovov",
            "Parné kotly okrem kotlov na centrálny ohrev teplej vody",
            "Zbrane a munícia",
            "Meče, tesáky, bodáky, kopije a podobné zbrane a ich časti",
            "Lode a plavidlá",
            "Rekreačné športové člny",
            "Železničné lokomotívy a vozový park",
            "Lietadlá a kozmické lode a podobné zariadenia",
            "Vojenské bojové vozidlá",
            "Pestovateľské celky trvalých porastov s dobou plodnosti dlhšou ako 3 roky",
            "Diaľkové telekomunikačné siete a vedenia",
        ],
    },
    {
        cislo: 5,
        dobaodpisovania: 20,
        dobaodpisovaniapripona: "rokov",
        coodpisujeme: [
            "Budovy okrem budov uvedených v odpisovej skupine 6",
            "Inžinierske stavby okrem stavieb uvedených v odpisových skupinách 4 a 6 a okrem jednotlivých oddeliteľných súčastí uvedených v odpisových skupinách 2 a 4",
        ],
    },
    {
        cislo: 6,
        dobaodpisovania: 40,
        dobaodpisovaniapripona: "rokov",
        coodpisujeme: [
            "Bytové budovy",
            "Hotely a podobné budovy",
            "Budovy pre administratívu",
            "Budovy pre kultúru a verejnú zábavu, vzdelávanie a zdravotníctvo",
            "Ostatné nebytové budovy okrem nebytových poľnohospodárskych budov, budovy a kasárne pre hasičov",
            "Ostatné inžinierske stavby",
        ],
    },
    // https://www.podnikajte.sk/odpisy/zaradovanie-majetku-do-odpisovych-skupin-2022-2023
]

export default odpisoveskupiny;